[package]
name = "chiavdf"
version = "1.1.11"
edition = "2021"
license = "Apache-2.0"
description = "Bindings to the chiavdf C++ library."
authors = ["Brandon Haggstrom <b.haggstrom@chia.net>"]
homepage = "https://github.com/Chia-Network/chiavdf"
repository = "https://github.com/Chia-Network/chiavdf"

[dependencies]
link-cplusplus = "1.0.9"

[build-dependencies]
bindgen = "0.71.1"
cmake = "0.1.52"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
